FROM frolvlad/alpine-glibc

# Install build dependencies and OpenSSL development libraries
RUN apk update && \
    apk add --no-cache \
    gcc \
    make \
    musl-dev \
    openssl-dev \
    lua5.1-dev \
    wget \
    unzip \
    openssl \
    git

# Install LuaRocks
RUN wget https://luarocks.org/releases/luarocks-3.8.0.tar.gz && \
    tar zxpf luarocks-3.8.0.tar.gz && \
    cd luarocks-3.8.0 && \
    ./configure && \
    make build && \
    make install && \
    cd .. && \
    rm -rf luarocks-3.8.0 luarocks-3.8.0.tar.gz

# Install Lua libraries
RUN luarocks install pgmoon && \
    luarocks install luasocket && \
    luarocks install luabitop && \
    luarocks install lua-cjson && \
    luarocks install luaossl CRYPTO_DIR=/usr

# Remove build dependencies
RUN apk del gcc make musl-dev wget

COPY your_script.lua .

# Copy Envoy binary into the container
COPY envoy /envoy
RUN chmod +x /envoy

# Copy Envoy configuration file
COPY envoy.yaml /etc/envoy.yaml

# Run Envoy
CMD ["/envoy", "-l", "info", "-c", "/etc/envoy.yaml", "--service-node", "front-node", "--service-cluster", "front-cluster"]
#CMD ["lua", "your_script.lua"]
