version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
      
  lua:
    build:
      context: .
      dockerfile: Dockerfile_lua
    depends_on:
      - postgres
    ports:
      - "8000:8000"  # Map MySQL port
