FROM frolvlad/alpine-glibc

RUN apk update && \
    apk add --no-cache \
    gcc \
    make \
    musl-dev \
    openssl-dev \
    luajit \
    luajit-dev \
    wget \
    unzip \
    openssl \
    git \
    mariadb-dev

# Install LuaRocks
RUN wget https://luarocks.org/releases/luarocks-3.8.0.tar.gz && \
    tar zxpf luarocks-3.8.0.tar.gz && \
    cd luarocks-3.8.0 && \
    ./configure --with-lua-include=/usr/include/luajit-2.1 && \
    make build && \
    make install && \
    cd .. && \
    rm -rf luarocks-3.8.0 luarocks-3.8.0.tar.gz

# Install Lua libraries
RUN luarocks install luasql-mysql MYSQL_INCDIR=/usr/include/mysql && \
    luarocks install luasocket && \
    luarocks install lua-cjson && \
    luarocks install luaossl CRYPTO_DIR=/usr

# Keep necessary runtime dependencies
RUN apk del gcc make musl-dev wget
RUN apk add --no-cache libstdc++ libgcc

COPY your_script.lua .
COPY envoy /envoy
RUN chmod +x /envoy
COPY envoy.yaml /etc/envoy.yaml

CMD ["/envoy", "-l", "info", "-c", "/etc/envoy.yaml", "--service-node", "front-node", "--service-cluster", "front-cluster"]